### PR TITLE
Spm support

### PR DESCRIPTION
**Pull request by bednarj4**
PR I want to make to the original TakeScoop repository but want to present it to you first. So please don't remove the branch after this PR is accepted.

### CODE REVIEW

**Comment by ghost** [comment]
Looks good to me!

Only minor thing is that I'm not sure whether I'd keep the iOS 13 CryptoKit code or just use CC unconditionally everywhere - it looks fine, but it does mean that there are two code paths, but only one will be tested in the unit tests (I guess the SwiftyRSA maintainers may have an opinion on this).

**Review by ghost — APPROVED** [review]
Looks good, see comment above.

**Comment by bednarj4** [comment]
> Looks good to me!
> 
> Only minor thing is that I'm not sure whether I'd keep the iOS 13 CryptoKit code or just use CC unconditionally everywhere - it looks fine, but it does mean that there are two code paths, but only one will be tested in the unit tests (I guess the SwiftyRSA maintainers may have an opinion on this).

Your right, will take care of that before closing this one, thanks!

**Review by buglam — APPROVED** [review]
Looks good! 🥇

**Pull request merged**
